/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {

	public static Injector doSetup() {
		return new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
