/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.ReservedLiteral;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reserved Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReservedLiteralImpl extends TerminalExpressionImpl implements ReservedLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReservedLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RESERVED_LITERAL;
  }

} //ReservedLiteralImpl
