/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_Reflex;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SReflex</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_ReflexImpl extends S_DeclarationImpl implements S_Reflex
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_ReflexImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SREFLEX;
  }

} //S_ReflexImpl
