/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_Set;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SSet</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_SetImpl extends S_AssignmentImpl implements S_Set
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_SetImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SSET;
  }

} //S_SetImpl
