/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_Var;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SVar</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_VarImpl extends S_DefinitionImpl implements S_Var
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_VarImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SVAR;
  }

} //S_VarImpl
