/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.speciesOrGridDisplayStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>species Or Grid Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class speciesOrGridDisplayStatementImpl extends StatementImpl implements speciesOrGridDisplayStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected speciesOrGridDisplayStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SPECIES_OR_GRID_DISPLAY_STATEMENT;
  }

} //speciesOrGridDisplayStatementImpl
