/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.VarFakeDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Var Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VarFakeDefinitionImpl extends VarDefinitionImpl implements VarFakeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarFakeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VAR_FAKE_DEFINITION;
  }

} //VarFakeDefinitionImpl
