/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.imageDisplayStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>image Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class imageDisplayStatementImpl extends StatementImpl implements imageDisplayStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected imageDisplayStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.IMAGE_DISPLAY_STATEMENT;
  }

} //imageDisplayStatementImpl
