/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_DirectAssignment;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SDirect Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_DirectAssignmentImpl extends S_AssignmentImpl implements S_DirectAssignment
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_DirectAssignmentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SDIRECT_ASSIGNMENT;
  }

} //S_DirectAssignmentImpl
