/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_Do;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SDo</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_DoImpl extends StatementImpl implements S_Do
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_DoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SDO;
  }

} //S_DoImpl
