/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.S_Solve;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>SSolve</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class S_SolveImpl extends StatementImpl implements S_Solve
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected S_SolveImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SSOLVE;
  }

} //S_SolveImpl
