/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.TypeFakeDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Type Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TypeFakeDefinitionImpl extends TypeDefinitionImpl implements TypeFakeDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TypeFakeDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TYPE_FAKE_DEFINITION;
  }

} //TypeFakeDefinitionImpl
