/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getBooleanLiteral()
 * @model
 * @generated
 */
public interface BooleanLiteral extends TerminalExpression
{
} // BooleanLiteral
