/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Equation Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getEquationFakeDefinition()
 * @model
 * @generated
 */
public interface EquationFakeDefinition extends EquationDefinition
{
} // EquationFakeDefinition
