/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Experiment File Structure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ExperimentFileStructure#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExperimentFileStructure()
 * @model
 * @generated
 */
public interface ExperimentFileStructure extends Entry
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(HeadlessExperiment)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getExperimentFileStructure_Exp()
   * @model containment="true"
   * @generated
   */
  HeadlessExperiment getExp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ExperimentFileStructure#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(HeadlessExperiment value);

} // ExperimentFileStructure
