/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends TerminalExpression
{
} // IntLiteral
