/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pragma</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Pragma#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Pragma#getPlugins <em>Plugins</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPragma()
 * @model
 * @generated
 */
public interface Pragma extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPragma_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Pragma#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Plugins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plugins</em>' containment reference.
   * @see #setPlugins(ExpressionList)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPragma_Plugins()
   * @model containment="true"
   * @generated
   */
  ExpressionList getPlugins();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Pragma#getPlugins <em>Plugins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plugins</em>' containment reference.
   * @see #getPlugins()
   * @generated
   */
  void setPlugins(ExpressionList value);

} // Pragma
