/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getVarFakeDefinition()
 * @model
 * @generated
 */
public interface VarFakeDefinition extends VarDefinition
{
} // VarFakeDefinition
