/*
 * generated by Xtext 2.23.0
 */
package org.xtext.example.mydsl.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.editor.quickfix.IQuickFixProvider;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.codeActions.QuickFixCodeActionService;
import org.eclipse.xtext.ide.server.commands.IExecutableCommandService;
import org.eclipse.xtext.ide.server.hover.HoverService;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.resource.ResourceServiceProviderServiceLoader;
import org.xtext.example.mydsl.ide.contentassist.MyDslIdeContentProposalProvider;

import com.google.inject.Binder;

/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
	public void configureExecutorService(Binder binder) {
	}

	public void configureIResourceDescriptionsLiveScope(Binder binder) {
//		binder.bind(IResourceServiceProvider.Registry.class).toProvider(ResourceServiceProviderServiceLoader.class);

	}

	public Class<? extends HoverService> bindHoverService() {
		return EclipseLikeHoverService.class;
	}

	public Class<? extends IExecutableCommandService> bindIExecutableCommandService() {
		return CommandService.class;
	}

	public Class<? extends IQuickFixProvider> bindIQuickFixProvider() {
		return MyDslIdeQuickfixProvider.class;
	}

	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return QuickFixCodeActionService.class;
	}

	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return MyDslIdeContentProposalProvider.class;
	}
}
