/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>image Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getimageDisplayStatement()
 * @model
 * @generated
 */
public interface imageDisplayStatement extends Statement
{
} // imageDisplayStatement
