/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SDirect Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getS_DirectAssignment()
 * @model
 * @generated
 */
public interface S_DirectAssignment extends S_Assignment
{
} // S_DirectAssignment
