/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>species Or Grid Display Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getspeciesOrGridDisplayStatement()
 * @model
 * @generated
 */
public interface speciesOrGridDisplayStatement extends Statement
{
} // speciesOrGridDisplayStatement
