/**
 * generated by Xtext 2.31.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Fake Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTypeFakeDefinition()
 * @model
 * @generated
 */
public interface TypeFakeDefinition extends TypeDefinition
{
} // TypeFakeDefinition
