/**
 * generated by Xtext unknown
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterators;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.Greeting;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final String fileName = URI.decode(resource.getURI().trimFileExtension().lastSegment());
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class ");
    _builder.append(fileName);
    _builder.append("Greeter {");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public static void main(String[] args) {");
    _builder.newLine();
    {
      Iterable<Greeting> _iterable = IteratorExtensions.<Greeting>toIterable(Iterators.<Greeting>filter(resource.getAllContents(), Greeting.class));
      for(final Greeting g : _iterable) {
        _builder.append("        ");
        _builder.append("System.out.println(\"Hello ");
        String _name = g.getName();
        _builder.append(_name, "        ");
        _builder.append(" ");
        {
          Greeting _from = g.getFrom();
          boolean _tripleNotEquals = (_from != null);
          if (_tripleNotEquals) {
            _builder.append(" from ");
            String _name_1 = g.getFrom().getName();
            _builder.append(_name_1, "        ");
          }
        }
        _builder.append("!\");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile((fileName + "Greeter.java"), _builder);
  }
}
